### PR TITLE
Added comment and changed style to improve clarity

### PR DESCRIPTION
**Pull request by NathanJPhillips**
Made the code better reflect its purpose and added comment in an attempt to get to grips with it in preparation for updating it to use multiple I2C addresses.

### CODE REVIEW

**Comment by pbugalski** [comment]
There is no reason for these changes.

**Comment by NathanJPhillips** [comment]
I made these changes to understand the code myself in order to write the fix for your outstanding issue regarding I2C address selection. Making your code clearer helps others contribute to it. If you don't want contributions then it would save people like me time to mention that in the readme.

**Comment by pbugalski** [comment]
I'm happy to see contributions which gives some improvement, not just different coding style.

**Comment by NathanJPhillips** [comment]
Would you like me to remove "style" changes and just leave the comment?

**Comment by pbugalski** [comment]
I don't like obvious comments, please focus on adding new functions if you wish to contribute.

**Comment by NathanJPhillips** [comment]
Unfortunately the things you think are obvious comments weren't obvious to me, having not done arm GPIO stuff before. Having looked up the things that I document here I was able to make a useful change. If this is added then other people would be able to add useful things too without going through the same process. I have split this up into multiple commits in case you wish to only cherry-pick some of it and so that you can better see what/why I have changed "style" things.

**Comment by pbugalski** [comment]
Lets leave this discussion and focus on new functionality. This project didn't support address selection, if you think it's necessary to add please do so. In terms of comments my favourite advise is to follow: https://www.kernel.org/doc/html/v4.10/process/coding-style.html#commenting
All information about registers is in MCU datasheet and code is not good place to copy that.

**Pull request closed without merging**
